server:
  port: 801
spring:
  application:
    name: cloud-order-service #服务名称
eureka:
  client:
    #true表示在注册中心注册自己 
    register-with-eureka: true
    #true是否从EurekaServer 抓取已有的注册信息，默认为true单节点无所谓 集群必须为true才可以配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka