server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    #false表示不在注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心，我的责任就是维护服务实例，并不要去检索
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址   查询服务和注册服务依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka
  #server:
    #enable-self-preservation: true  #自我保护开启 不配置也为true  关闭为false
    #eviction-interval-timer-in-ms: 2000    改变心跳时间 单位是毫秒

devtools:
  restart:
    enabled: true  #设置开启热部署
    additional-paths: src/main/java #重启目录
    exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效