server:
  port: 7001
eureka:
  instance:
    hostname: localhost
  client:
    #false表示不在注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心，我的责任就是维护服务实例，并不要去检索
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址   查询服务和注册服务依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka


devtools:
  restart:
    enabled: true  #设置开启热部署
    additional-paths: src/main/java #重启目录
    exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效